CREATE SEQUENCE SEQ_MEMBER;

CREATE TABLE TBL_MEMBER (
	MEMBER_ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_IDENTIFICATION VARCHAR2(500) CONSTRAINT UK_MEMBER UNIQUE NOT NULL,
	MEMBER_PASSWORD VARCHAR2(1000) NOT NULL
);

SELECT * FROM TBL_MEMBER;

DROP TABLE TBL_MEMBER;
